### 1. Login to get Token
# @name login
POST http://127.0.0.1:8000/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=admin123

### Variable setup for automated testing
@token = {{login.response.body.access_token}}

### 2. Create a Skill
POST http://127.0.0.1:8000/admin/skills
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cloud Computing",
    "description": "Azure basics and deployment"
}

### 3. Create a Student (Using Skill ID 1)
POST http://127.0.0.1:8000/admin/students
Authorization: Bearer {{ "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc3MjU2MjgyN30.r1AYnOcyat7zTts4UVMGFZwDbFaSrSR_pxwgTUk8JJc",}}
Content-Type: application/json

{
    "full_name": "Azure Student",
    "email": "student@azure.com",
    "enrollment_id": "EDU-001",
    "skill_id": 1
}

### 4. Get Dashboard Stats
GET http://127.0.0.1:8000/admin/dashboard
Authorization: Bearer {{token}}

### 5. List Students (Paginated)
GET http://127.0.0.1:8000/admin/students?skip=0&limit=10
Authorization: Bearer {{token}}